// Add mock data for testing purposes

export const mockEvent = {
  id: "1",
  title: "اجتماع نادي الكتاب الشهري",
  description:
    "انضم إلينا في اجتماع نادي الكتاب الشهري حيث سنناقش كتاب 'مئة عام من العزلة' للكاتب غابرييل غارسيا ماركيز. سيكون هناك مناقشة مفتوحة وتبادل للآراء حول الكتاب، بالإضافة إلى أنشطة أدبية متنوعة.",
  date: "2023-12-15",
  start_time: "2023-12-15T18:00:00Z",
  end_time: "2023-12-15T20:00:00Z",
  location_name: "مكتبة المدينة المركزية",
  address: "شارع الاستقلال، تقسيم، إسطنبول",
  category: "cultural",
  image_url: "/book-club.png",
  provider_id: "1",
  capacity: 30,
  price: null,
  is_free: true,
  demo_profiles: {
    email: "bookclub@example.com",
    profile_image_url: "/provider-abstract.png",
    business_name: "نادي الكتاب العربي",
  },
  // Añadir campos adicionales que podrían faltar
  created_at: "2023-01-01T00:00:00Z",
  updated_at: "2023-01-01T00:00:00Z",
}

export const mockEvents = [
  mockEvent,
  {
    id: "2",
    title: "فعالية التواصل التجاري",
    description:
      "فرصة رائعة للتواصل مع رواد الأعمال والمهنيين في مجال الأعمال. ستتضمن الفعالية محادثات ملهمة، وفرص للتواصل، وورش عمل تفاعلية.",
    date: "2023-12-20",
    start_time: "2023-12-20T09:00:00",
    end_time: "2023-12-20T17:00:00",
    location_name: "فندق الريتز كارلتون",
    address: "سيشان، إسطنبول",
    category: "business",
    image_url: "/business-networking.png",
    provider_id: "2",
    capacity: 100,
    price: 250,
    is_free: false,
    demo_profiles: {
      email: "business@example.com",
      profile_image_url: "/provider-abstract.png",
      business_name: "شبكة الأعمال العربية",
    },
    created_at: "2023-01-01T00:00:00",
    updated_at: "2023-01-01T00:00:00",
  },
  {
    id: "3",
    title: "مهرجان الأفلام المحلي",
    description:
      "مهرجان سينمائي يعرض أفلاماً من صناع الأفلام المحليين والعالميين. سيتضمن المهرجان عروضاً خاصة، ومناقشات مع المخرجين، وورش عمل سينمائية.",
    date: "2023-12-25",
    start_time: "2023-12-25T14:00:00",
    end_time: "2023-12-25T22:00:00",
    location_name: "سينما المدينة",
    address: "بيوغلو، إسطنبول",
    category: "entertainment",
    image_url: "/film-festival.png",
    provider_id: "3",
    capacity: 200,
    price: 50,
    is_free: false,
    demo_profiles: {
      email: "film@example.com",
      profile_image_url: "/provider-abstract.png",
      business_name: "مهرجان الأفلام العربية",
    },
  },
  {
    id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
    title: "فعالية اختبار",
    description: "هذه فعالية اختبار لمعالجة الأخطاء",
    date: "2023-12-31",
    start_time: "2023-12-31T12:00:00Z",
    end_time: "2023-12-31T14:00:00Z",
    location_name: "مكان الاختبار",
    address: "عنوان الاختبار، إسطنبول",
    category: "other",
    image_url: "/community-event.png",
    provider_id: "test",
    capacity: 50,
    price: null,
    is_free: true,
    demo_profiles: {
      email: "test@example.com",
      profile_image_url: "/provider-abstract.png",
      business_name: "اختبار",
    },
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
]
